# .air.toml — fixed version

# Air runs from /app (because of WORKDIR /app in Dockerfile)
root = "."
tmp_dir = "tmp"

# Build and binary output
cmd = "go build -o ./transactions ./main.go"
bin = "./transactions"

# File extensions to watch
include_ext = ["go", "tpl", "tmpl", "html"]

# Directories to ignore
exclude_dir = ["assets", "tmp", "vendor"]

# Log build errors to file
log = "air_errors.log"
stop_on_error = true
send_interrupt = true
poll = true
poll_interval = 500
delay = 1000

[log]
time = true

[color]
main = "yellow"
watcher = "cyan" 
build = "blue"
runner = "green"

[misc]
clean_on_exit = true
