// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/functions.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transfer a specific amount from one user to another
type TransferFundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // UUID (char(36))
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // UUID (char(36))
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                            // In smallest denomination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFundsRequest) Reset() {
	*x = TransferFundsRequest{}
	mi := &file_proto_functions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFundsRequest) ProtoMessage() {}

func (x *TransferFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFundsRequest.ProtoReflect.Descriptor instead.
func (*TransferFundsRequest) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{0}
}

func (x *TransferFundsRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *TransferFundsRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *TransferFundsRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferFundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransferId    string                 `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // TigerBeetle-generated ID (string representation of Uint128)
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFundsResponse) Reset() {
	*x = TransferFundsResponse{}
	mi := &file_proto_functions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFundsResponse) ProtoMessage() {}

func (x *TransferFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFundsResponse.ProtoReflect.Descriptor instead.
func (*TransferFundsResponse) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{1}
}

func (x *TransferFundsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferFundsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferFundsResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferFundsResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Create a TigerBeetle account for a user
type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`           // Stored in UserData128
	Bank          bool                   `protobuf:"varint,3,opt,name=bank,proto3" json:"bank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_functions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAccountRequest) GetBank() bool {
	if x != nil {
		return x.Bank
	}
	return false
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Same as user_id (UUID)
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_functions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateAccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Get current balance for a given account
type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromTime      uint64                 `protobuf:"varint,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"` // UnixMicro
	ToTime        uint64                 `protobuf:"varint,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_functions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceRequest) GetFromTime() uint64 {
	if x != nil {
		return x.FromTime
	}
	return 0
}

func (x *GetBalanceRequest) GetToTime() uint64 {
	if x != nil {
		return x.ToTime
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DebitsPosted  uint64                 `protobuf:"varint,3,opt,name=debits_posted,json=debitsPosted,proto3" json:"debits_posted,omitempty"`
	CreditsPosted uint64                 `protobuf:"varint,4,opt,name=credits_posted,json=creditsPosted,proto3" json:"credits_posted,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_functions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBalanceResponse) GetDebitsPosted() uint64 {
	if x != nil {
		return x.DebitsPosted
	}
	return 0
}

func (x *GetBalanceResponse) GetCreditsPosted() uint64 {
	if x != nil {
		return x.CreditsPosted
	}
	return 0
}

func (x *GetBalanceResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Get most recent transfer for account
type GetMovementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromTime      uint64                 `protobuf:"varint,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime        uint64                 `protobuf:"varint,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	Limit         bool                   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovementsRequest) Reset() {
	*x = GetMovementsRequest{}
	mi := &file_proto_functions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovementsRequest) ProtoMessage() {}

func (x *GetMovementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovementsRequest.ProtoReflect.Descriptor instead.
func (*GetMovementsRequest) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{6}
}

func (x *GetMovementsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMovementsRequest) GetFromTime() uint64 {
	if x != nil {
		return x.FromTime
	}
	return 0
}

func (x *GetMovementsRequest) GetToTime() uint64 {
	if x != nil {
		return x.ToTime
	}
	return 0
}

func (x *GetMovementsRequest) GetLimit() bool {
	if x != nil {
		return x.Limit
	}
	return false
}

type GTResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromUsername  string                 `protobuf:"bytes,2,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	ToUsername    string                 `protobuf:"bytes,3,opt,name=to_username,json=toUsername,proto3" json:"to_username,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GTResult) Reset() {
	*x = GTResult{}
	mi := &file_proto_functions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GTResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GTResult) ProtoMessage() {}

func (x *GTResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GTResult.ProtoReflect.Descriptor instead.
func (*GTResult) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{7}
}

func (x *GTResult) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *GTResult) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *GTResult) GetToUsername() string {
	if x != nil {
		return x.ToUsername
	}
	return ""
}

func (x *GTResult) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GTResult) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetMovementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Movements     []*GTResult            `protobuf:"bytes,3,rep,name=movements,proto3" json:"movements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovementsResponse) Reset() {
	*x = GetMovementsResponse{}
	mi := &file_proto_functions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovementsResponse) ProtoMessage() {}

func (x *GetMovementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_functions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovementsResponse.ProtoReflect.Descriptor instead.
func (*GetMovementsResponse) Descriptor() ([]byte, []int) {
	return file_proto_functions_proto_rawDescGZIP(), []int{8}
}

func (x *GetMovementsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMovementsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMovementsResponse) GetMovements() []*GTResult {
	if x != nil {
		return x.Movements
	}
	return nil
}

var File_proto_functions_proto protoreflect.FileDescriptor

const file_proto_functions_proto_rawDesc = "" +
	"\n" +
	"\x15proto/functions.proto\x12\tfunctions\"n\n" +
	"\x14TransferFundsRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"\x8a\x01\n" +
	"\x15TransferFundsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vtransfer_id\x18\x03 \x01(\tR\n" +
	"transferId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"_\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04bank\x18\x03 \x01(\bR\x04bank\"\x82\x01\n" +
	"\x15CreateAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"b\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfrom_time\x18\x02 \x01(\x04R\bfromTime\x12\x17\n" +
	"\ato_time\x18\x03 \x01(\x04R\x06toTime\"\xb2\x01\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rdebits_posted\x18\x03 \x01(\x04R\fdebitsPosted\x12%\n" +
	"\x0ecredits_posted\x18\x04 \x01(\x04R\rcreditsPosted\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"z\n" +
	"\x13GetMovementsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfrom_time\x18\x02 \x01(\x04R\bfromTime\x12\x17\n" +
	"\ato_time\x18\x03 \x01(\x04R\x06toTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\bR\x05limit\"\xa7\x01\n" +
	"\bGTResult\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12#\n" +
	"\rfrom_username\x18\x02 \x01(\tR\ffromUsername\x12\x1f\n" +
	"\vto_username\x18\x03 \x01(\tR\n" +
	"toUsername\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"}\n" +
	"\x14GetMovementsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\tmovements\x18\x03 \x03(\v2\x13.functions.GTResultR\tmovements2\xc7\x02\n" +
	"\x12TransactionService\x12L\n" +
	"\aAccount\x12\x1f.functions.CreateAccountRequest\x1a .functions.CreateAccountResponse\x12M\n" +
	"\bTransfer\x12\x1f.functions.TransferFundsRequest\x1a .functions.TransferFundsResponse\x12F\n" +
	"\aBalance\x12\x1c.functions.GetBalanceRequest\x1a\x1d.functions.GetBalanceResponse\x12L\n" +
	"\tMovements\x12\x1e.functions.GetMovementsRequest\x1a\x1f.functions.GetMovementsResponseB\x06Z\x04pb/.b\x06proto3"

var (
	file_proto_functions_proto_rawDescOnce sync.Once
	file_proto_functions_proto_rawDescData []byte
)

func file_proto_functions_proto_rawDescGZIP() []byte {
	file_proto_functions_proto_rawDescOnce.Do(func() {
		file_proto_functions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_functions_proto_rawDesc), len(file_proto_functions_proto_rawDesc)))
	})
	return file_proto_functions_proto_rawDescData
}

var file_proto_functions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_functions_proto_goTypes = []any{
	(*TransferFundsRequest)(nil),  // 0: functions.TransferFundsRequest
	(*TransferFundsResponse)(nil), // 1: functions.TransferFundsResponse
	(*CreateAccountRequest)(nil),  // 2: functions.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 3: functions.CreateAccountResponse
	(*GetBalanceRequest)(nil),     // 4: functions.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 5: functions.GetBalanceResponse
	(*GetMovementsRequest)(nil),   // 6: functions.GetMovementsRequest
	(*GTResult)(nil),              // 7: functions.GTResult
	(*GetMovementsResponse)(nil),  // 8: functions.GetMovementsResponse
}
var file_proto_functions_proto_depIdxs = []int32{
	7, // 0: functions.GetMovementsResponse.movements:type_name -> functions.GTResult
	2, // 1: functions.TransactionService.Account:input_type -> functions.CreateAccountRequest
	0, // 2: functions.TransactionService.Transfer:input_type -> functions.TransferFundsRequest
	4, // 3: functions.TransactionService.Balance:input_type -> functions.GetBalanceRequest
	6, // 4: functions.TransactionService.Movements:input_type -> functions.GetMovementsRequest
	3, // 5: functions.TransactionService.Account:output_type -> functions.CreateAccountResponse
	1, // 6: functions.TransactionService.Transfer:output_type -> functions.TransferFundsResponse
	5, // 7: functions.TransactionService.Balance:output_type -> functions.GetBalanceResponse
	8, // 8: functions.TransactionService.Movements:output_type -> functions.GetMovementsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_functions_proto_init() }
func file_proto_functions_proto_init() {
	if File_proto_functions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_functions_proto_rawDesc), len(file_proto_functions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_functions_proto_goTypes,
		DependencyIndexes: file_proto_functions_proto_depIdxs,
		MessageInfos:      file_proto_functions_proto_msgTypes,
	}.Build()
	File_proto_functions_proto = out.File
	file_proto_functions_proto_goTypes = nil
	file_proto_functions_proto_depIdxs = nil
}
